import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

VALUEFIRST_AUTH = os.getenv("VALUEFIRST_AUTH_TOKEN")
VALUEFIRST_SENDER = os.getenv("VALUEFIRST_SENDER", "CONCNT")
TWOFACTOR_API_KEY = os.getenv("TWOFACTOR_API_KEY")

JWT_SECRET = os.getenv("JWT_SECRET_KEY", "supersecretkey")
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "60"))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS", "30"))
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")

