import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

VALUEFIRST_AUTH = os.getenv("VALUEFIRST_AUTH_TOKEN")
VALUEFIRST_SENDER = os.getenv("VALUEFIRST_SENDER", "CONCNT")
TWOFACTOR_API_KEY = os.getenv("TWOFACTOR_API_KEY")

JWT_SECRET = os.getenv("JWT_SECRET_KEY", "supersecretkey")
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "60"))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS", "30"))
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")

DIVINE_API_KEY = "e19094a2dca050c96e919b1cd387daf8"
DIVINE_AUTH_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2RpdmluZWFwaS5jb20vc2lnbnVwIiwiaWF0IjoxNzU3NzAwNDU2LCJuYmYiOjE3NTc3MDA0NTYsImp0aSI6IlNKYXByd2tEakpiMmVONkQiLCJzdWIiOiI0MjU1IiwicHJ2IjoiZTZlNjRiYjBiNjEyNmQ3M2M2Yjk3YWZjM2I0NjRkOTg1ZjQ2YzlkNyJ9.29enOtioW_1_i5nUYXBtt5-5sDaQeVoFulZTfCQf184"